# Generated by Django 5.1.6 on 2025-05-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_alter_home_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone1", models.CharField(max_length=20)),
                ("phone2", models.CharField(max_length=20)),
                ("email1", models.EmailField(max_length=254)),
                ("email2", models.EmailField(max_length=254)),
                ("address1", models.CharField(max_length=255)),
                ("address2", models.CharField(max_length=255)),
            ],
        ),
    ]
