# Generated by Django 5.1.6 on 2025-07-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_comment_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="body_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blog",
            name="body_ru",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blog",
            name="body_uz",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blog",
            name="title_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="blog",
            name="title_ru",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="blog",
            name="title_uz",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="name_en",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="category",
            name="name_ru",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="category",
            name="name_uz",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="content_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="content_ru",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="content_uz",
            field=models.TextField(null=True),
        ),
    ]
