# Generated by Django 5.1.6 on 2025-02-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_blog_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.SlugField(blank=True),
        ),
    ]
