# Generated by Django 5.1.6 on 2025-02-27 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_home"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
