# Generated by Django 5.1.6 on 2025-05-01 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_delete_blog_delete_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name_plural': 'Home'},
        ),
    ]
